### get schools
# curl 'http://localhost:8080/schools' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: nl,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Cookie: pcetest=10-03-2022' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'Cache-Control: max-age=0'
GET http://localhost:8080/school
Content-Type: application/json

### create school
POST http://localhost:8080/school
Content-Type: application/json

{ "name" : "Willem-Alexanderschool", "address" : "Dwarsstraat 13", "postalCode" : "5432 AZ", "contactPersonName" : "John Doe", "contactPersonEmail"  : "john.doe@willemalexanderschool.nl"}

### get 1 school
GET http://localhost:8080/school/1
Content-Type: application/json

### get school by name
GET http://localhost:8080/school/name/Willem-Alexanderschool
Content-Type: application/json
