### get schools
GET http://localhost:8080/api/v1/school
Content-Type: application/json

### create school
POST http://localhost:8080/api/v1/school
Content-Type: application/json

{ "name" : "Willem-Alexanderschool", "address" : "Dwarsstraat 13", "postalCode" : "5432 AZ", "contactPersonName" : "John Doe", "contactPersonEmail"  : "john.doe@willemalexanderschool.nl"}

### get 1 school
GET http://localhost:8080/api/v1/school/928a2e50-60ee-40d8-b55c-15394fbcdd16
Content-Type: application/json

### get school by name
GET http://localhost:8080/api/v1/school/name/Willem-Alexanderschool
Content-Type: application/json
