quarkus:
  datasource:
    db-kind: mariadb
  hibernate-orm:
    database:
      generation: none
  log:
    level: INFO
  oidc:
    auth-server-url: ${AUTHSERVER:dev-g60bne29.eu.auth0.com}
    client-id: ${CLIENTID:1MWGJlOHqjqNHiPZKEY5R4C7fsQySr9k}
    credentials:
      secret: ${AUTH0SECRET}
    application-type: service
    authentication:
      scopes: openid,profile,email
  smallrye-openapi:
    store-schema-directory: "target/generated"

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: "mariadb:10.6"
    log:
      category:
        "org.littil":
          level: DEBUG
    hibernate-orm:
      log:
        sql: true
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: "mariadb:10.6"
    log:
      category:
        "org.littil":
          level: INFO
    hibernate-orm:
      database:
        generation: none
      log:
        sql: false
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata

"%prod":
  quarkus:
    banner:
      enabled: false