quarkus:
  datasource:
    db-kind: mariadb
  hibernate-orm:
    database:
      generation: none
  log:
    level: INFO
  swagger-ui:
    oauth-client-id: ${OIDC_CLIENT_ID}
  smallrye-openapi:
    store-schema-directory: "target/generated"
    oauth2-implicit-authorization-url: ${OIDC_TENANT}/authorize?audience=${OIDC_TENANT}/api/v2/ # we add audience as query param to make sure we get a token with payload
    oidc-open-id-connect-url: ${OIDC_TENANT}/authorize
    security-scheme-name: Auth0
    security-scheme: oauth2-implicit
    oauth-scopes: [openid, email, profile]
  oidc:
    client-id: ${OIDC_CLIENT_ID}
    auth-server-url: ${OIDC_TENANT}/auth
    credentials:
      secret: ${OIDC_CLIENT_SECRET}
      jwt:
        audience: ${OIDC_TENANT}/api/v2/
    token:
      audience: ${OIDC_TENANT}/api/v2/
    introspection-path: .well-known/openid-configuration
    jwks-path: .well-known/jwks.json

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: "mariadb:10.6"
    log:
      category:
        "org.littil":
          level: DEBUG
        "quarkus.oidc":
          level: DEBUG
    oidc:
    hibernate-orm:
      log:
        sql: true
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: "mariadb:10.6"
    log:
      category:
        "org.littil":
          level: INFO
    hibernate-orm:
      database:
        generation: none
      log:
        sql: false
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata

"%prod":
  quarkus:
    banner:
      enabled: false
    datasource:
      username: ${DATASOURCE_USERNAME:littil}
      password: ${DATASOURCE_PASSWORD:littil}
      jdbc:
        url: jdbc:mariadb://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DATASOURCE_DATABASE:littil}
