---
name: Code and depencendies analysis

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: mvn -v
      - run: mvn -B package
      - uses: actions/upload-artifact@v2
        with:
           path: target/*.jar
